### ISSUE TITLE
h3jsr API change

### ISSUE THREAD

**Issue by obrl-soil** [Curycu/valuemap#1]
Hi,

a new version of `h3jsr` is now available (v.1.3.0) which has some breaking API changes. Since your package is on CRAN as a strong dependency, this means you will need to make some changes in response, and resubmit.

For your package I can see you're only using `h3jsr::h3_to_polygon()`, so its an easy fix. The best option is to 

1. change the function call to its new name, `h3jsr::cell_to_polygon()` - everything else about it works the same.
2. change your DESCRIPTION to import `h3jsr (>= v 1.3.0)`

This will give you the latest version of the package and will be stable going forward.

**Comment by Curycu** [comment]
Thank you for notice~! I will do update on my package side  

1. I will set dependency h3jsr (<= 1.2.3) on CRAN first
2. when you update h3jsr package on CRAN 1.3.0
3. I will set dependency h3jsr (>= 1.3.0) on CRAN then

**Comment by Curycu** [comment]
@obrl-soil 
I'm trying to update for h3jsr (== 1.2.3) on CRAN first, but CRAN side checking error keep occurs and I'm not sure why that error keep occurs only on CRAN side (R-hub checking & local windows platform checking have no error cases)

``` CRAN windows platform only error
* checking package dependencies ... ERROR
Package required and available but unsuitable version: 'h3jsr'
```

So... my conclusion is : 
please just update your h3jsr package to 1.3.0 on CRAN when you available.
after your package updated on CRAN, I will try to update valuemap package.

+ for Github package : valuemap package already updated to v2.0.3 for responding to h3jsr v1.3.0 api change
